# Generated by Django 6.0.7 on 2026-07-26 05:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating score from 1 to 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Review comment or description.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the review was created.')),
                ('post', models.ForeignKey(help_text='The deal/post this review is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.marketplacepost')),
                ('reviewee', models.ForeignKey(help_text='The user being rated/reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='The user leaving the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketplace Review',
                'verbose_name_plural': 'Marketplace Reviews',
                'db_table': 'marketplace_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'reviewer')},
            },
        ),
    ]
