# Generated by Django 6.0 on 2026-07-10 15:47

from django.db import migrations


def populate_product_counts(apps, schema_editor):
    """Populate initial product counts for all categories"""
    Category = apps.get_model('catalog', 'Category')
    
    # Update product counts for all categories
    for category in Category.objects.all():
        product_count = category.products.count()
        category.product_count = product_count
        category.save(update_fields=['product_count'])


def reverse_populate_product_counts(apps, schema_editor):
    """Reset all product counts to 0"""
    Category = apps.get_model('catalog', 'Category')
    Category.objects.all().update(product_count=0)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_update_product_counts'),
    ]

    operations = [
        migrations.RunPython(
            populate_product_counts,
            reverse_populate_product_counts
        ),
    ]
