# Generated by Django 6.0 on 2026-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_populate_product_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
    ]
