import { ChatMessage, CartItem, PantryItem, Group, Product } from './types'

export const mockChatFlow: ChatMessage[] = [
  {
    id: '1',
    sender: 'ai',
    text: 'Hello! I\'m NeedNow, your AI shopping assistant. What would you like to cook or prepare today?',
    timestamp: new Date(Date.now() - 5 * 60000),
    quickReplies: ['Butter Chicken', 'Pasta', 'Salad', 'Breakfast'],
  },
  {
    id: '2',
    sender: 'user',
    text: 'Butter Chicken',
    timestamp: new Date(Date.now() - 4 * 60000),
  },
  {
    id: '3',
    sender: 'ai',
    text: 'Great choice! Butter chicken is delicious. Let me find the best ingredients for you.',
    timestamp: new Date(Date.now() - 3.5 * 60000),
  },
  {
    id: '4',
    sender: 'ai',
    text: 'How many servings would you like to make?',
    timestamp: new Date(Date.now() - 3 * 60000),
    quickReplies: ['2 servings', '4 servings', '6 servings'],
  },
  {
    id: '5',
    sender: 'user',
    text: '4 servings',
    timestamp: new Date(Date.now() - 2 * 60000),
  },
  {
    id: '6',
    sender: 'ai',
    text: 'Perfect! I\'ve added the essential ingredients to your cart: chicken breast, tomato sauce, cream, and spices. Do you want to add any optional items?',
    timestamp: new Date(Date.now() - 60000),
    quickReplies: ['Yes, add more', 'No, that\'s all', 'Show me the cart'],
  },
  {
    id: '7',
    sender: 'user',
    text: 'Show me the cart',
    timestamp: new Date(),
  },
]

export const mockCartItems: CartItem[] = [
  {
    id: 'c1',
    name: 'Chicken Breast',
    description: '500g, fresh and tender',
    price: 450,
    quantity: 1,
    category: 'Essential',
  },
  {
    id: 'c2',
    name: 'Tomato Sauce',
    description: '400ml, premium quality',
    price: 120,
    quantity: 1,
    category: 'Essential',
  },
  {
    id: 'c3',
    name: 'Heavy Cream',
    description: '200ml, pure dairy',
    price: 180,
    quantity: 1,
    category: 'Essential',
  },
  {
    id: 'c4',
    name: 'Garam Masala',
    description: '100g, aromatic blend',
    price: 95,
    quantity: 1,
    category: 'Essential',
  },
  {
    id: 'c5',
    name: 'Turmeric Powder',
    description: '50g, pure turmeric',
    price: 45,
    quantity: 1,
    category: 'Essential',
  },
  {
    id: 'c6',
    name: 'Onions',
    description: '500g, fresh',
    price: 60,
    quantity: 1,
    category: 'Essential',
  },
  {
    id: 'c7',
    name: 'Garlic Paste',
    description: '200g, freshly made',
    price: 75,
    quantity: 1,
    category: 'Essential',
  },
  {
    id: 'c8',
    name: 'Butter',
    description: '100g, salted butter',
    price: 110,
    quantity: 1,
    category: 'Optional',
  },
  {
    id: 'c9',
    name: 'Basmati Rice',
    description: '1kg, premium quality',
    price: 280,
    quantity: 1,
    category: 'Optional',
  },
  {
    id: 'c10',
    name: 'Naan Bread',
    description: '4 pieces, freshly baked',
    price: 120,
    quantity: 1,
    category: 'Luxury',
  },
  {
    id: 'c11',
    name: 'Mango Lassi',
    description: '500ml, homemade style',
    price: 95,
    quantity: 1,
    category: 'Luxury',
  },
]

export const mockPantryItems: PantryItem[] = [
  {
    id: 'p1',
    name: 'Flour',
    category: 'Grains',
    quantity: 2,
    unit: 'kg',
    expiryDate: new Date(Date.now() + 60 * 24 * 60000),
    icon: '🌾',
  },
  {
    id: 'p2',
    name: 'Olive Oil',
    category: 'Oils',
    quantity: 500,
    unit: 'ml',
    expiryDate: new Date(Date.now() + 180 * 24 * 60000),
    icon: '🫒',
  },
  {
    id: 'p3',
    name: 'Milk',
    category: 'Dairy',
    quantity: 1,
    unit: 'L',
    expiryDate: new Date(Date.now() + 5 * 24 * 60000),
    icon: '🥛',
  },
  {
    id: 'p4',
    name: 'Eggs',
    category: 'Eggs',
    quantity: 12,
    unit: 'pieces',
    expiryDate: new Date(Date.now() + 30 * 24 * 60000),
    icon: '🥚',
  },
  {
    id: 'p5',
    name: 'Cheese',
    category: 'Dairy',
    quantity: 500,
    unit: 'g',
    expiryDate: new Date(Date.now() + 15 * 24 * 60000),
    icon: '🧀',
  },
  {
    id: 'p6',
    name: 'Honey',
    category: 'Sweeteners',
    quantity: 1,
    unit: 'kg',
    expiryDate: new Date(Date.now() + 365 * 24 * 60000),
    icon: '🍯',
  },
]

export const mockGroups: Group[] = [
  {
    id: 'g1',
    name: 'Weekly Groceries',
    members: [
      { id: 'm1', name: 'Alice', avatar: '👩' },
      { id: 'm2', name: 'Bob', avatar: '👨' },
      { id: 'm3', name: 'Carol', avatar: '👩‍🦱' },
    ],
    itemCount: 24,
    totalPrice: 3450,
  },
  {
    id: 'g2',
    name: 'Office Supplies',
    members: [
      { id: 'm4', name: 'David', avatar: '👨‍💼' },
      { id: 'm5', name: 'Eve', avatar: '👩‍💼' },
    ],
    itemCount: 12,
    totalPrice: 1200,
  },
  {
    id: 'g3',
    name: 'Party Planning',
    members: [
      { id: 'm6', name: 'Frank', avatar: '🧑' },
      { id: 'm7', name: 'Grace', avatar: '👩‍🦰' },
      { id: 'm8', name: 'Henry', avatar: '👨‍🦱' },
      { id: 'm9', name: '+1 more', avatar: '👥' },
    ],
    itemCount: 48,
    totalPrice: 5680,
  },
]

export const mockProducts: Product[] = [
  {
    id: 'prod1',
    name: 'Wireless Earbuds Pro',
    description: 'True wireless with noise cancellation',
    price: 2999,
    rating: 4.5,
    reviews: 324,
    tags: ['Electronics', 'Audio', 'Wireless'],
    category: 'Electronics',
  },
  {
    id: 'prod2',
    name: 'AirPods Max',
    description: 'Premium over-ear headphones with spatial audio',
    price: 59999,
    rating: 4.8,
    reviews: 156,
    tags: ['Electronics', 'Premium', 'Headphones'],
    category: 'Electronics',
  },
  {
    id: 'prod3',
    name: 'Bluetooth Headphones',
    description: 'Comfortable fit with 30-hour battery life',
    price: 1899,
    rating: 4.3,
    reviews: 512,
    tags: ['Electronics', 'Audio', 'Budget-Friendly'],
    category: 'Electronics',
  },
  {
    id: 'prod4',
    name: 'Basmati Rice Premium',
    description: 'Long grain aromatic basmati rice 1kg',
    price: 280,
    rating: 4.6,
    reviews: 428,
    tags: ['Groceries', 'Rice', 'Premium'],
    category: 'Groceries',
  },
  {
    id: 'prod5',
    name: 'Heavy Cream Organic',
    description: 'Pure organic heavy cream 200ml',
    price: 240,
    rating: 4.4,
    reviews: 218,
    tags: ['Groceries', 'Dairy', 'Organic'],
    category: 'Groceries',
  },
  {
    id: 'prod6',
    name: 'Garam Masala Blend',
    description: 'Authentic Indian spice blend 100g',
    price: 95,
    rating: 4.7,
    reviews: 643,
    tags: ['Groceries', 'Spices', 'Authentic'],
    category: 'Groceries',
  },
  {
    id: 'prod7',
    name: 'Fresh Naan Bread',
    description: 'Freshly baked Indian naan bread pack of 4',
    price: 120,
    rating: 4.5,
    reviews: 356,
    tags: ['Groceries', 'Bakery', 'Fresh'],
    category: 'Groceries',
  },
  {
    id: 'prod8',
    name: 'Eco Dish Soap',
    description: 'Biodegradable dishwashing liquid 500ml',
    price: 145,
    rating: 4.2,
    reviews: 289,
    tags: ['Cleaning', 'Eco-Friendly', 'Natural'],
    category: 'Cleaning',
  },
  {
    id: 'prod9',
    name: 'Paper Towels Jumbo',
    description: 'Ultra absorbent paper towel roll pack of 12',
    price: 320,
    rating: 4.3,
    reviews: 502,
    tags: ['Cleaning', 'Household', 'Bulk'],
    category: 'Cleaning',
  },
  {
    id: 'prod10',
    name: 'Vitamin C Serum',
    description: 'Brightening vitamin C face serum 30ml',
    price: 599,
    rating: 4.6,
    reviews: 734,
    tags: ['Personal Care', 'Skincare', 'Vitamin C'],
    category: 'Personal Care',
  },
  {
    id: 'prod11',
    name: 'Natural Shampoo Bar',
    description: 'Eco-friendly solid shampoo bar for all hair types',
    price: 249,
    rating: 4.4,
    reviews: 418,
    tags: ['Personal Care', 'Eco-Friendly', 'Hair Care'],
    category: 'Personal Care',
  },
  {
    id: 'prod12',
    name: 'Moisturizer Cream',
    description: 'Hydrating facial moisturizer with natural oils 50ml',
    price: 399,
    rating: 4.5,
    reviews: 567,
    tags: ['Personal Care', 'Skincare', 'Natural'],
    category: 'Personal Care',
  },
]

export const mockCategories = [
  {
    id: 'cat1',
    name: 'Electronics',
    icon: '📱',
    color: 'from-blue-500 to-purple-500',
    productCount: 3,
  },
  {
    id: 'cat2',
    name: 'Groceries',
    icon: '🛒',
    color: 'from-green-500 to-emerald-500',
    productCount: 4,
  },
  {
    id: 'cat3',
    name: 'Personal Care',
    icon: '🧴',
    color: 'from-pink-500 to-rose-500',
    productCount: 3,
  },
  {
    id: 'cat4',
    name: 'Home & Kitchen',
    icon: '🏠',
    color: 'from-orange-500 to-amber-500',
    productCount: 2,
  },
  {
    id: 'cat5',
    name: 'Cleaning',
    icon: '🧹',
    color: 'from-cyan-500 to-blue-500',
    productCount: 2,
  },
  {
    id: 'cat6',
    name: 'Health',
    icon: '💊',
    color: 'from-red-500 to-pink-500',
    productCount: 2,
  },
]

export const mockPriceRanges = [
  { id: 'price1', label: '₹0 - ₹500', min: 0, max: 500 },
  { id: 'price2', label: '₹500 - ₹2,000', min: 500, max: 2000 },
  { id: 'price3', label: '₹2,000 - ₹10,000', min: 2000, max: 10000 },
  { id: 'price4', label: '₹10,000+', min: 10000, max: 999999 },
]

export const mockRatingRanges = [
  { id: 'rating1', label: '4.5+ Stars', min: 4.5 },
  { id: 'rating2', label: '4.0+ Stars', min: 4.0 },
  { id: 'rating3', label: '3.5+ Stars', min: 3.5 },
]
