# Generated by Django 6.0.7 on 2026-07-26 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='A short bio introducing the user to the local marketplace community.')),
                ('location_name', models.CharField(blank=True, help_text="Text representation of the user's primary marketplace location.", max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for radius calculations.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for radius calculations.', max_digits=9, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating calculated from reviews received.', max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0, help_text='Total number of reviews received.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the marketplace profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the profile details were last updated.')),
                ('user', models.OneToOneField(help_text='The core authenticated user linked to this marketplace profile.', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketplace Profile',
                'verbose_name_plural': 'Marketplace Profiles',
                'db_table': 'marketplace_profiles',
            },
        ),
    ]
