# Generated by Django 6.0 on 2026-07-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_password_hash_user_neon_auth_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Unique username (optional)', max_length=50, null=True),
        ),
    ]
