# Generated by Django 6.0 on 2026-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_userinteraction_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='last_calculated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last preference score calculation (used for incremental decay).', null=True),
        ),
    ]
