# Generated by Django 6.0 on 2026-07-09 13:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_category_image_url_alter_product_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the collection (e.g., Home, Apartment, Office)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the collection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Collection',
                'verbose_name_plural': 'Asset Collections',
                'db_table': 'asset_collections',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the location (e.g., Kitchen, Pantry, Fridge)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='asset.assetcollection')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent location for nested structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='asset.assetlocation')),
            ],
            options={
                'verbose_name': 'Asset Location',
                'verbose_name_plural': 'Asset Locations',
                'db_table': 'asset_locations',
                'ordering': ['name'],
                'unique_together': {('collection', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Current quantity owned', validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.PositiveIntegerField(default=1, help_text='Alert when quantity falls below this level', validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_date', models.DateField(blank=True, help_text='When the item was purchased', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='When the item expires (if applicable)', null=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='When the item was last used/consumed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this asset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_assets', to='catalog.product')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset.assetcollection')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset.assetlocation')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
                'ordering': ['-updated_at'],
                'unique_together': {('collection', 'product', 'location')},
            },
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('add', 'Add'), ('consume', 'Consume'), ('adjust', 'Adjust'), ('remove', 'Remove'), ('move', 'Move')], max_length=20)),
                ('quantity_before', models.PositiveIntegerField(help_text='Quantity before the transaction')),
                ('quantity_after', models.PositiveIntegerField(help_text='Quantity after the transaction')),
                ('quantity_changed', models.IntegerField(help_text='Change in quantity (positive or negative)')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('order', 'Order'), ('ai', 'AI Suggestion')], default='manual', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Additional note about the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='asset.asset')),
            ],
            options={
                'verbose_name': 'Asset Transaction',
                'verbose_name_plural': 'Asset Transactions',
                'db_table': 'asset_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
