# Generated by Django 6.0 on 2026-07-12 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_product_popularity_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_scores', models.JSONField(default=dict)),
                ('brand_scores', models.JSONField(default=dict)),
                ('tag_scores', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('cart', 'Cart'), ('wishlist', 'Wishlist'), ('purchase', 'Purchase'), ('rating', 'Rating'), ('search', 'Search')], max_length=20)),
                ('value', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='recommendat_user_id_d77068_idx'), models.Index(fields=['product'], name='recommendat_product_1eaa6e_idx'), models.Index(fields=['interaction_type'], name='recommendat_interac_31ee41_idx'), models.Index(fields=['created_at'], name='recommendat_created_d7e264_idx'), models.Index(fields=['user', 'interaction_type'], name='recommendat_user_id_ef4939_idx'), models.Index(fields=['user', 'product'], name='recommendat_user_id_44f668_idx')],
            },
        ),
    ]
