# Generated by Django 6.0.7 on 2026-07-26 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplacePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('need', 'Need'), ('sell', 'Sell')], help_text='Whether this is a request (Need) or a listing (Sell).', max_length=10)),
                ('title', models.CharField(help_text="Short title of the post (e.g., 'Need Physics book today').", max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the item needed or being sold.')),
                ('category', models.CharField(help_text='Category of the item (e.g., Books, Electronics, Home, etc.).', max_length=100)),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs associated with the post.')),
                ('location_name', models.CharField(help_text='Text representation of the location where the post is active.', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinates of the location.', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinates of the location.', max_digits=9)),
                ('radius', models.FloatField(default=5.0, help_text='Proximity radius in kilometers for matching nearby feeds.')),
                ('urgency', models.CharField(blank=True, choices=[('today', 'Today'), ('week', 'This Week'), ('flexible', 'Flexible')], help_text='Urgency of the need (Only applicable for Need posts).', max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Max budget limit (Only applicable/optional for Need posts).', max_digits=10, null=True)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], help_text='Condition of the item (Only applicable for Sell posts).', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price of the item (Only applicable for Sell posts).', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', help_text='Current state of the listing/need.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the post was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the post was last modified.')),
                ('owner', models.ForeignKey(help_text='The user who created this post.', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketplace Post',
                'verbose_name_plural': 'Marketplace Posts',
                'db_table': 'marketplace_posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post_type'], name='marketplace_post_ty_d294c7_idx'), models.Index(fields=['status'], name='marketplace_status_34a3c5_idx'), models.Index(fields=['latitude', 'longitude'], name='marketplace_latitud_15adea_idx')],
            },
        ),
    ]
