# Generated by Django 6.0.7 on 2026-07-26 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_marketplacepost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='The proposed price for the transaction.', max_digits=10)),
                ('message', models.TextField(help_text='Detailed message/proposal from the offer maker.')),
                ('images', models.JSONField(blank=True, default=list, help_text='Optional list of image URLs showing the item condition.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Current state of the offer.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the offer was made.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the offer state was last changed.')),
                ('post', models.ForeignKey(help_text='The post this offer is responding to.', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.marketplacepost')),
                ('user', models.ForeignKey(help_text='The user making the offer.', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketplace Offer',
                'verbose_name_plural': 'Marketplace Offers',
                'db_table': 'marketplace_offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='marketplace_status_65b23c_idx'), models.Index(fields=['created_at'], name='marketplace_created_f8c262_idx')],
            },
        ),
    ]
