# Generated by Django 6.0.7 on 2026-07-26 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplaceoffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Text content of the message.')),
                ('image_url', models.URLField(blank=True, help_text='Optional URL of an image shared in the chat.', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read by the recipient.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was sent.')),
                ('post', models.ForeignKey(blank=True, help_text='The post this chat thread belongs to (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='marketplace.marketplacepost')),
                ('recipient', models.ForeignKey(help_text='The user who receives this message.', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='The user who sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'marketplace_chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient'], name='marketplace_sender__5ce580_idx'), models.Index(fields=['created_at'], name='marketplace_created_d53c71_idx'), models.Index(fields=['is_read'], name='marketplace_is_read_589b76_idx')],
            },
        ),
    ]
