# Generated by Django 6.0 on 2026-07-31 14:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_marketplacereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplacePostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/posts/')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marketplaceoffer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marketplacepost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marketplaceprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marketplacereview',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='marketplace_sender__5ce580_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='marketplace_created_d53c71_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='marketplace_is_read_589b76_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketplaceoffer',
            name='marketplace_status_65b23c_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketplaceoffer',
            name='marketplace_created_f8c262_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketplacepost',
            name='marketplace_post_ty_d294c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketplacepost',
            name='marketplace_status_34a3c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='marketplacepost',
            name='marketplace_latitud_15adea_idx',
        ),
        migrations.AlterUniqueTogether(
            name='marketplacereview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/chat/'),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='visibility_radius',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='marketplaceprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/profile/'),
        ),
        migrations.AddField(
            model_name='marketplaceprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplaceprofile',
            name='seller_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('student', 'Student'), ('home_business', 'Home Business'), ('verified_business', 'Verified Business')], default='individual', max_length=30),
        ),
        migrations.AddField(
            model_name='marketplaceprofile',
            name='trust_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='marketplace.marketplacepost'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketplaceoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketplaceoffer',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='marketplaceoffer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.marketplacepost'),
        ),
        migrations.AlterField(
            model_name='marketplaceoffer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='marketplaceoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplaceoffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='condition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='location_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='post_type',
            field=models.CharField(choices=[('sell', 'Sell'), ('need', 'Need'), ('rent', 'Rent'), ('exchange', 'Exchange'), ('donate', 'Donate'), ('service', 'Service')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='urgency',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marketplaceprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.marketplacepost'),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='reviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marketplacereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='marketplaceoffer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='marketplacepost',
            table=None,
        ),
        migrations.AlterModelTable(
            name='marketplaceprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='marketplacereview',
            table=None,
        ),
        migrations.AddField(
            model_name='marketplacecomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='marketplace.marketplacepost'),
        ),
        migrations.AddField(
            model_name='marketplacecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketplacepostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.marketplacepost'),
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='marketplaceoffer',
            name='images',
        ),
        migrations.RemoveField(
            model_name='marketplaceoffer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='marketplacepost',
            name='images',
        ),
        migrations.RemoveField(
            model_name='marketplacepost',
            name='radius',
        ),
    ]
